version: '3'

services:
  NISTReto:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - NIST_API_KEY=7a9dcca6-cedb-40e9-b242-567cb4f6f405
